Upgrade decidim to v0.21
CodiTramuntana/decidim-codit-demo-app pull request #14
Opened 2020-08-19 10:56 UTC by tramuntanal

Upgrades Decidim to latest 0.21-stable branch.

Also:
- Upgrade to Ruby v2.6.6.
- Upgrade geocoder to v1.6 (implies changing Here api key)

2020-08-20 06:36 UTC, victorol1 approved these changes
LGTM

2020-08-20 06:38 UTC, victorol1 requested changes
I just realized we are missing the time zone upgrade note! https://github.com/CodiTramuntana/decidim-codit-demo-app/blob/upgrade/to_v0.21/config/application.rb#L16

2020-08-20 11:33 UTC, tramuntanal commented
good catch @victorol1 !
I've removed the time-zone configuration

2020-08-21 07:16 UTC, victorol1 approved these changes

2020-08-25 08:52 UTC, merged