Update to Decidim 0.27
CodiTramuntana/decidim-codit-demo-app pull request #55
Opened 2024-01-24 13:14 UTC by laurajaime

Upgrade to 0.27: https://github.com/decidim/decidim/releases/tag/v0.27.0

- [ ] Pending to review and merge: https://github.com/gencat/decidim-module-challenges/pull/68

2024-01-29 17:24 UTC, tramuntanal requested changes
Some small things to review please

2024-01-29 17:24 UTC, tramuntanal commented on config/environments/production.rb
> +  config.active_job.queue_adapter = :sidekiq
??

2024-01-29 17:24 UTC, tramuntanal commented on config/schedule.rb
>    rake "decidim:metrics:all"
only `decidim:metrics:all` and `decidim:open_data:export` cronjobs for 0.27?
I think that at least we also need `decidim:delete_data_portability_files`. As we deploy in a server, `tmp:clear` will also be good every night.

2024-01-29 17:24 UTC, tramuntanal commented on public/sw.js.br
Should not be in `.gitignore`?

2024-01-29 17:24 UTC, tramuntanal commented on public/sw.js.gz
Should not be in `.gitignore`?

2024-01-29 17:24 UTC, tramuntanal commented on public/sw.js.map.br
Should not be in `.gitignore`?

2024-01-29 17:24 UTC, tramuntanal commented on public/sw.js.map.gz
Should not be in `.gitignore`?

2024-02-01 10:27 UTC, laurajaime commented
@tramuntanal the chrome version in github actions has been updated, but Decidim in version 0.27 is not updated for this version. Since the chrome driver cannot be updated, the tests fail.

It seems that they will soon make a backport to 0.27 (https://github.com/decidim/decidim/pull/12351#issuecomment-1919154131), meanwhile we can merge when you do approve. The tests have passed locally.

2024-02-05 16:50 UTC, tramuntanal reviewed
Ok @laurajaime , let's do it like you say.

but first, challenges module branch in the Gemfile should be corrected

2024-02-05 16:50 UTC, tramuntanal commented on Gemfile
> +gem "decidim-challenges", git: "https://github.com/gencat/decidim-module-challenges", branch: "bump/ruby_version"
incorrect branch

2024-02-05 17:21 UTC, laurajaime commented on Gemfile
> +gem "decidim-challenges", git: "https://github.com/gencat/decidim-module-challenges", branch: "bump/ruby_version"
done

2024-02-05 17:28 UTC, tramuntanal approved these changes

2024-02-06 09:49 UTC, merged